
// System.debug('Drink coffee');
// System.debug('Clean');

// AsyncUtil.boilWater();

// System.debug('Chop the onion');
// System.debug('Sit back and relax');
// System.debug('Continue to cook'); 

 
// List<Lead> myLeads = Utils.getLeads('Jon Snow', 'NightWatch Inc',true, 1000); 
// System.debug('myLeads.size()  value is : ' + myLeads.size() );


MyLeadBatchProcessor mlp=new MyLeadBatchProcessor();
Database.executeBatch(mlp, 150);
