// Bird1 b1 = new Bird1('Tweety', 'parakeet', 1, 'small');

// b1.fly();
// b1.chirp();
// b1.eat();
// b1.move();

// Bird1 b1 = new Bird1('Tweety', 'parakeet', 1, 'small');
// Cat1 c1 = new Cat1('Tom', 'Tabby', 4, 'medium');
//Lion l1 = new Lion('Simba', 'Mountain Lion', 5, 'large' );
//Animal1 a1=new Animal1('Simba', 'Mountain Lion', 5, 'large' );

//a1.move();
// b1.eat();
// b1.move();
// c1.eat();
// l1.eat();
// b1.fly();
Animal1 a2= new Cat1('Simba', 'Mountain Lion', 5, 'large' );

